# RUN: %blang %s -emit=mlir-affine -opt 2>&1 | FileCheck %s
# RUN: %blang %s -emit=mlir-llvm -opt 2>&1 | FileCheck %s --check-prefix=CHECK-LLVM
# RUN: %blang %s -emit=jit -opt 2>&1 | FileCheck %s --check-prefix=CHECK-JIT

fn main() {
  var c : float64 = 2;
  print(c);
}

# CHECK:   %cst = constant 2.000000e+00 : f64
# CHECK:   "blang.print"(%cst) : (f64) -> ()
# CHECK:   return

# CHECK-LLVM:  %0 = llvm.mlir.constant(2.000000e+00 : f64) : !llvm.double
# CHECK-LLVM:  llvm.call @printf({{.*}}, {{.*}}) : (!llvm<"i8*">, !llvm.double) -> !llvm.i32
# CHECK-LLVM:  llvm.return

# CHECK-JIT: 2.000000
