# RUN: %blang %s -emit=mlir-affine -opt 2>&1 | FileCheck %s
# RUN: %blang %s -emit=mlir-llvm -opt 2>&1 | FileCheck %s --check-prefix=CHECK-LLVM
# RUN: %blang %s -emit=jit -opt 2>&1 | FileCheck %s --check-prefix=CHECK-JIT

fn main() {
  var c : int = 2;
  print(c);
}

# CHECK:   %c2_i32 = constant 2 : i32
# CHECK:   "blang.print"(%c2_i32) : (i32) -> ()
# CHECK:   return

# CHECK-LLVM:  %0 = llvm.mlir.constant(2 : i32) : !llvm.i32
# CHECK-LLVM:  llvm.call @printf({{.*}}, {{.*}}) : (!llvm<"i8*">, !llvm.i32) -> !llvm.i32
# CHECK-LLVM:  llvm.return

# CHECK-JIT: 2
